# config file for transcriptome assembly and post-processing the scNapBar results

# samples/path to scNapBar results - minimap2 alignments
# the scNapBar results (real.label) must be under the same directory
# results are written one directory up into a directory called "analysis"

samples:
 H61211a: /prj/Florian_Leuschner_spatial/analysis/Nanopore/VX06_H61211a/results/VX06_H61211a_all_pass.bam
 H61211b: /prj/Florian_Leuschner_spatial/analysis/Nanopore/VX06_H61211b/results/VX06_H61211b_all_pass.bam
 H61211c: /prj/Florian_Leuschner_spatial/analysis/Nanopore/VX06_H61211c/results/VX06_H61211c_all_pass.bam
 H61211d: /prj/Florian_Leuschner_spatial/analysis/Nanopore/VX06_H61211d/results/VX06_H61211d_all_pass.bam
 
 
# ------------- assembly 

# genome
fasta: /prj/Florian_Leuschner_spatial/analysis/Nanopore/mm10-2020-A_build/Mus_musculus.GRCm38.dna.primary_assembly.fa.modified
 
# stringtie2/gffcompare
strg_base: /prj/Florian_Leuschner_spatial/analysis/Nanopore/transcriptomes
gtf: /prj/Florian_Leuschner_spatial/analysis/Nanopore/mm10-2020-A_build/gencode.vM23.primary_assembly.annotation.gtf.filtered
# use existing annotation as guide for stringtie
use_guide: True
# additional options passed to stringtie
# we use -L (enforces -s 1.5 -g 0) by default
strg_opts: "-v --conservative" # -t -c 1.5 -f 0.05
strg_merge_opts: "-v"
# options passed to gffcompare:
gffcmp_opts: "-V -R"

# gffread/minimap2 index (transcriptome)
idx_base: /prj/Florian_Leuschner_spatial/analysis/Nanopore/mm10-2020-A_build
idx_name: Mus_musculus_GRCm38_transcripts

# minimap2 transcriptome index
minimap_idx_opts: "-k 14"


# ------------- sc-nanopore-utils 

# transcriptome sequences and minimap index are derived from the 
# above using "strg_base", "idx_base", and "idx_name"

# minimap transcriptome mapping
minimap_opts: "-v1 -2 -ax map-ont -N 100 -p 0.99 --MD"
# we currently use the environment modules ** see note below
# if False, then salmon must be available on your path
salmon_env: /biosw/salmon/1.5.2/bin/salmon
# salmon alignment-based mode (quant -a)
# salmon_opts: "-l A --noErrorModel --noLengthCorrection --fldMean 925 --fldMax 300000" # prior to --ont
# we use --ont by default
salmon_opts: "-l A --fldMean 925 --fldMax 300000"


# ------------- visiumtools

# NOTE: Only relevant for Visium Spatial Gene Expression!

# path to CellRanger output (Illumina)
# same as used for scNapBar

samples_cellranger:
 H61211a: /prj/Florian_Leuschner_spatial/Illumina/VX06_A006200151/cellranger/VX06_A1_149524/outs
 H61211b: /prj/Florian_Leuschner_spatial/Illumina/VX06_A006200151/cellranger/VX06_B1_149525/outs
 H61211c: /prj/Florian_Leuschner_spatial/Illumina/VX06_A006200151/cellranger/VX06_C1_149526/outs
 H61211d: /prj/Florian_Leuschner_spatial/Illumina/VX06_A006200151/cellranger/VX06_D1_149527/outs

