#!/bin/bash

#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -p long
#SBATCH --mem=150G
#SBATCH --job-name="iso"
#SBATCH --mail-user=eboileau@uni-heidelberg.de

# conda activate scNapBar-spatial
# module load salmon/1.5.2

CFG=/prj/Florian_Leuschner_spatial/analysis/Nanopore/ScNaST/workflow/config.yaml
LOG=/prj/Florian_Leuschner_spatial/analysis/Nanopore/ScNaST/workflow/sc-nanopore-utils/logs/sc-nanopore-utils.log
./get_iso_mtx.py $CFG --use-slurm --tmp /scratch/global_tmp/ --num-cpus 40 --logging-level INFO --log-file $LOG


# NOTE:
# if salmon is unable to assign enough fragments (using default --minAssignedFrags 10) for the "last" barcode
# in the loop (run_salmon), slurm fails and terminates...
